import type { CountryCardData } from "./country-card";

export const TRENDING_COUNTRIES: CountryCardData[] = [
  {
    id: "BE",
    country: "Belgium",
    slug: "belgium",
    imageUrl: "/Redfox Country images/Belgium.png",
    estimatedRate: "₹570/kg",
    ordersDelivered: "20k+",
    deliveryTime: "2–5 days",
  },
  {
    id: "FR",
    country: "France",
    slug: "france",
    imageUrl: "/Redfox Country images/France.png",
    estimatedRate: "₹630/kg",
    ordersDelivered: "20k+",
    deliveryTime: "6–9 days",
  },
  {
    id: "CH",
    country: "Switzerland",
    slug: "switzerland",
    imageUrl: "/Redfox Country images/Switzerland.png",
    estimatedRate: "₹450/kg",
    ordersDelivered: "8k+",
    deliveryTime: "3–6 days",
  },
  {
    id: "SG",
    country: "Singapore",
    slug: "singapore",
    imageUrl: "/Redfox Country images/Singapore.png",
    estimatedRate: "₹870/kg",
    ordersDelivered: "20k+",
    deliveryTime: "2–4 days",
  },
  {
    id: "KR",
    country: "South Korea",
    slug: "south-korea",
    imageUrl: "/Redfox Country images/South Korea.png",
    estimatedRate: "₹550/kg",
    ordersDelivered: "8k+",
    deliveryTime: "3–4 days",
  },
  {
    id: "US",
    country: "USA",
    slug: "usa",
    imageUrl: "/Redfox Country images/USA.png",
    estimatedRate: "₹650/kg",
    ordersDelivered: "20k+",
    deliveryTime: "6–8 days",
  },
  {
    id: "CA",
    country: "Canada",
    slug: "canada",
    imageUrl: "/Redfox Country images/Canada.png",
    estimatedRate: "₹660/kg",
    ordersDelivered: "20k+",
    deliveryTime: "5–8 days",
  },
  {
    id: "DE",
    country: "Germany",
    slug: "germany",
    imageUrl: "/Redfox Country images/Germany.png",
    estimatedRate: "₹570/kg",
    ordersDelivered: "20k+",
    deliveryTime: "4–5 days",
  },
  {
    id: "IT",
    country: "Italy",
    slug: "italy",
    imageUrl: "/Redfox Country images/Italy.png",
    estimatedRate: "₹540/kg",
    ordersDelivered: "20k+",
    deliveryTime: "3–7 days",
  },
  {
    id: "GB",
    country: "UK",
    slug: "uk",
    imageUrl: "/Redfox Country images/London.png", // since you have London.png
    estimatedRate: "₹760/kg",
    ordersDelivered: "20k+",
    deliveryTime: "4–6 days",
  },
  {
    id: "JP",
    country: "Japan",
    slug: "japan",
    imageUrl: "/Redfox Country images/Japan.png",
    estimatedRate: "₹330/kg",
    ordersDelivered: "20k+",
    deliveryTime: "5–9 days",
  },
  {
    id: "AE",
    country: "Dubai",
    slug: "dubai",
    imageUrl: "/Redfox Country images/Dubai.png",
    estimatedRate: "₹660/kg",
    ordersDelivered: "20k+",
    deliveryTime: "4–6 days",
  },
  {
    id: "CN",
    country: "China",
    slug: "china",
    imageUrl: "/Redfox Country images/China.png",
    estimatedRate: "₹890/kg",
    ordersDelivered: "20k+",
    deliveryTime: "4–7 days",
  },
  {
    id: "MY",
    country: "Malaysia",
    slug: "malaysia",
    imageUrl: "/Redfox Country images/Malaysia.png",
    estimatedRate: "₹650/kg",
    ordersDelivered: "20k+",
    deliveryTime: "3–5 days",
  },
  {
    id: "SA",
    country: "Saudi Arabia",
    slug: "saudi-arabia",
    imageUrl: "/Redfox Country images/Saudi-Arabia.png",
    estimatedRate: "₹900/kg",
    ordersDelivered: "8k+",
    deliveryTime: "5–7 days",
  },
];